"""Generate sine and gradient tables for the demo as assembly includes."""
import math
import sys

def gen_sine_table():
    """256-byte sine table, values 0-63 (center 32, amplitude ±31)."""
    lines = ["; Sine table: 256 bytes, values 0-63"]
    lines.append("sine_table:")
    for i in range(0, 256, 16):
        vals = []
        for j in range(16):
            v = int(32 + 31 * math.sin(2 * math.pi * (i + j) / 256))
            v = max(0, min(63, v))
            vals.append(f"${v:02X}")
        lines.append(f"\tdc.b\t{','.join(vals)}")
    return "\n".join(lines)

def gen_gradient_table():
    """256-word gradient table: rainbow bars with dark gaps."""
    lines = ["; Gradient table: 256 words (Amiga RGB4 colors)"]
    lines.append("gradient_table:")
    colors = []
    for i in range(256):
        # Create 3 raster bars using raised cosine envelopes
        brightness = 0.0
        for bar in range(3):
            center = 43 + bar * 72  # bar centers at ~43, 115, 187
            dist = abs(i - center)
            if dist < 28:
                brightness = max(brightness, 0.5 + 0.5 * math.cos(math.pi * dist / 28))

        if brightness < 0.05:
            colors.append(0x000)
            continue

        # HSV rainbow: hue rotates with position
        hue = (i * 3) % 360
        h = hue / 60.0
        sector = int(h) % 6
        frac = h - int(h)
        v = brightness
        p = 0
        q = v * (1 - frac)
        t = v * frac

        if sector == 0:   r, g, b = v, t, p
        elif sector == 1: r, g, b = q, v, p
        elif sector == 2: r, g, b = p, v, t
        elif sector == 3: r, g, b = p, q, v
        elif sector == 4: r, g, b = t, p, v
        else:             r, g, b = v, p, q

        ri = min(15, int(r * 15 + 0.5))
        gi = min(15, int(g * 15 + 0.5))
        bi = min(15, int(b * 15 + 0.5))
        colors.append((ri << 8) | (gi << 4) | bi)

    for i in range(0, 256, 8):
        vals = [f"${colors[i+j]:04X}" for j in range(8)]
        lines.append(f"\tdc.w\t{','.join(vals)}")
    return "\n".join(lines)

def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "tables.i"
    content = "; Auto-generated by gentables.py — do not edit\n\n"
    content += gen_sine_table() + "\n\n"
    content += gen_gradient_table() + "\n"
    with open(out, "w") as f:
        f.write(content)
    print(f"Written {out}")

if __name__ == "__main__":
    main()
